In [11]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import cv2

In [50]:
datadir = './cat and dog/PetImages'
CATEGORIES = ['Cat','Dog']
training_data = []
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(datadir, category)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array,(50,50))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
            
create_training_data()


In [20]:
print(len(training_data))

24946


In [21]:
import random
random.shuffle(training_data)

In [35]:
X = []
y = []
for features, label in training_data:
    X.append(features)
    y.append(label)

In [36]:
X

[array([[ 67,  64, 107, ...,  60,  75,  73],
        [ 80,  52,  94, ...,  67,  61,  71],
        [ 72,  87,  74, ...,  71,  61,  67],
        ...,
        [226, 224, 218, ..., 132, 126, 122],
        [222, 222, 227, ..., 112, 117, 119],
        [226, 231, 222, ..., 118, 117, 114]], dtype=uint8),
 array([[132, 122, 125, ..., 127, 130, 115],
        [128, 128, 119, ..., 124, 127, 121],
        [147, 118, 129, ..., 100, 124, 117],
        ...,
        [106, 142, 146, ..., 238, 218, 226],
        [148, 149, 150, ..., 168, 213, 237],
        [153, 152, 156, ..., 142, 218, 226]], dtype=uint8),
 array([[11, 12, 14, ..., 13, 12, 11],
        [13, 13, 15, ..., 13, 12, 12],
        [ 9, 10, 11, ...,  5, 14,  7],
        ...,
        [11, 27,  8, ...,  1,  2,  3],
        [ 8, 25,  4, ...,  0,  2,  3],
        [ 2,  2,  2, ...,  6,  2,  2]], dtype=uint8),
 array([[ 33,  31,  79, ..., 135, 138, 144],
        [ 33,  27,  55, ..., 137, 137, 143],
        [ 35,  25,  37, ..., 137, 137, 141],
       

In [44]:
X = np.array(X).reshape(-1,50,50,1)

In [66]:
X.shape


(24946, 50, 50, 1)

In [67]:
X= X/255

In [51]:
import pickle
pickle_out = open("X.pickle","wb")
pickle.dump(X,pickle_out)
pickle_out.close()

pickle_out = open("Y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten, MaxPooling2D, Conv2D

In [68]:
model = Sequential()

model.add(Conv2D(64, (3,3),input_shape= X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(128,(3,3),input_shape= X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation("relu"))

model.add(Dense(1))
model.add(Activation("sigmoid"))

model.compile(loss="binary_crossentropy",
             optimizer="adam",
             metrics=["accuracy"])

model.fit(X,y,batch_size=32,validation_split=0.1,epochs = 3)




Train on 22451 samples, validate on 2495 samples
Epoch 1/3
22451/22451 [==============================] - 10s 460us/step - loss: 0.5845 - acc: 0.6865 - val_loss: 0.5391 - val_acc: 0.7226
Epoch 2/3
22451/22451 [==============================] - 9s 420us/step - loss: 0.4894 - acc: 0.7656 - val_loss: 0.4892 - val_acc: 0.7663
Epoch 3/3
22451/22451 [==============================] - 9s 422us/step - loss: 0.4374 - acc: 0.7972 - val_loss: 0.4548 - val_acc: 0.7924
