In [1255]:
import pandas as pd
import numpy as np

In [1256]:
data = pd.read_csv('./data/train.csv')
# pd.read_csv('./data/creditcard.csv')

In [1257]:
data = data.drop(['Loan_ID'],axis =1)

In [1258]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.6+ KB


In [1259]:
data['Gender'].nunique()

2

In [1260]:
data.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [1261]:
gender = {'Male':1, 'Female':0}

In [1262]:
data['Education'].nunique()

2

In [1263]:
data['Gender'] = data['Gender'].map(gender)

In [1264]:
married = {'Yes':1,'No':0}
data['Married'] = data['Married'].map(married)

In [1265]:
Education = {'Graduate':1,'Not Graduate':0}
data['Education'] = data['Education'].map(Education)

In [1266]:
Self_Employed = {'Yes':1,'No':0}
data['Self_Employed'] = data['Self_Employed'].map(Self_Employed)

In [1267]:
data.Property_Area.unique()
Property_Area = {'Urban':0 , 'Rural':1, 'Semiurban':2 }
data['Property_Area'] = data['Property_Area'].map(Property_Area)


In [1268]:
data.describe()

Gender     Married   Education  Self_Employed  ApplicantIncome  \
count  601.000000  611.000000  614.000000     582.000000       614.000000   
mean     0.813644    0.651391    0.781759       0.140893      5403.459283   
std      0.389718    0.476920    0.413389       0.348211      6109.041673   
min      0.000000    0.000000    0.000000       0.000000       150.000000   
25%      1.000000    0.000000    1.000000       0.000000      2877.500000   
50%      1.000000    1.000000    1.000000       0.000000      3812.500000   
75%      1.000000    1.000000    1.000000       0.000000      5795.000000   
max      1.000000    1.000000    1.000000       1.000000     81000.000000   

       CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
count         614.000000  592.000000         600.00000      564.000000   
mean         1621.245798  146.412162         342.00000        0.842199   
std          2926.248369   85.587325          65.12041        0.364878   
min             0.000000    9.000000          12.00000        0.000000   
25%             0.000000  100.000000         360.00000        1.000000   
50%          1188.500000  128.000000         360.00000        1.000000   
75%          2297.250000  168.000000         360.00000        1.000000   
max         41667.000000  700.000000         480.00000        1.000000   

       Property_Area  
count     614.000000  
mean        1.050489  
std         0.840875  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         2.000000  
max         2.000000

In [1269]:
from sklearn.preprocessing import MinMaxScaler

In [1270]:
scaler = MinMaxScaler()
data['ApplicantIncome']= scaler.fit_transform(data[['ApplicantIncome']])

D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [1271]:
data['Dependents'].unique()
Dependents = {'0':0,'1':1,'2':2,'3+':3}
data['Dependents'] = data['Dependents'].map(Dependents)

In [1272]:
data['Loan_Amount_Term']= scaler.fit_transform(data[['Loan_Amount_Term']])

In [1273]:
data[['CoapplicantIncome','LoanAmount']]= scaler.fit_transform(data[['CoapplicantIncome','LoanAmount']])

In [1274]:
Loan_Status = {'Y':1,'N':0}
data['Loan_Status'] = data['Loan_Status'].map(Loan_Status)

In [1275]:
data = data.dropna()
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 480 entries, 1 to 613
Data columns (total 12 columns):
Gender               480 non-null float64
Married              480 non-null float64
Dependents           480 non-null float64
Education            480 non-null int64
Self_Employed        480 non-null float64
ApplicantIncome      480 non-null float64
CoapplicantIncome    480 non-null float64
LoanAmount           480 non-null float64
Loan_Amount_Term     480 non-null float64
Credit_History       480 non-null float64
Property_Area        480 non-null int64
Loan_Status          480 non-null int64
dtypes: float64(9), int64(3)
memory usage: 48.8 KB


In [1276]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

In [1277]:
data['Loan_Status']

1      0
2      1
3      1
4      1
5      1
6      1
7      0
8      1
9      0
10     1
12     1
13     0
14     1
15     1
17     0
18     0
20     0
21     1
22     0
25     1
26     1
27     1
28     0
31     0
32     0
33     1
34     0
37     1
38     1
39     1
      ..
575    1
577    1
578    1
580    1
581    0
582    1
584    0
585    0
586    1
587    1
589    0
590    1
591    0
593    1
594    1
595    1
596    0
598    1
599    1
602    1
603    1
604    1
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 480, dtype: int64

In [1278]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data.iloc[:,:-1],data.iloc[:,-1:],test_size=0.2, stratify =data['Loan_Status'] )
clf = BernoulliNB()


In [1279]:
clf.fit(Xtrain,Ytrain)

D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [1280]:
clf.predict(Xtest)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [1281]:
from sklearn.ensemble import RandomForestClassifier

In [1282]:
clf = RandomForestClassifier(n_estimators=1, max_depth=1,
...                              random_state=0)

In [1283]:
clf.fit(Xtrain,Ytrain)

D:\Tools\Programs\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=1, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [1284]:
clf.feature_importances_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [1285]:
y_pred =clf.predict(Xtest)

In [1286]:
from sklearn.metrics import accuracy_score

In [1287]:
accuracy_score(Ytest,y_pred)

0.8229166666666666

In [1288]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [1289]:
from sklearn import svm

In [1290]:
clf = svm.SVC(gamma='scale')
clf.fit(Xtrain, Ytrain)


D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [1291]:
ypred = clf.predict(Xtest)

In [1292]:
accuracy_score(Ytest,ypred)

0.8229166666666666

In [1293]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

In [1294]:
Ytrain.shape  

(384, 1)

In [1295]:
# clf = svm.SVC(gamma='scale')
# clf = svm.SVC(kernel='poly', probability=True, degree=2)
clf = svm.SVC(kernel='rbf', probability=True)
clf = svm.SVC(kernel='linear')
# clf = DecisionTreeClassifier()
# clf = RandomForestClassifier(n_estimators=100, max_depth=5,random_state=0)

In [1296]:
score = cross_val_score(clf, Xtrain, Ytrain, cv=k_fold, n_jobs=1, scoring='accuracy')


D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Tools\Programs\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_

In [1297]:
score

array([0.71794872, 0.76923077, 0.84615385, 0.84615385, 0.97368421,
       0.71052632, 0.78947368, 0.78947368, 0.89473684, 0.71052632])

In [1298]:
round(np.mean(score)*100, 2)

80.48

In [1299]:
80.94

80.94